apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
        - name: cursos
          image: robertraul/cursos:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-msvc-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cm-msvc-cursos
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: cm-msvc-cursos
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: password
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: cm-msvc-cursos
                  key: usuario_url
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8001
#              scheme: HTTP
#            initialDelaySeconds: 5
#            periodSeconds: 20
#            timeoutSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8001
#              scheme: HTTP
#            initialDelaySeconds: 10
#            periodSeconds: 30
#            timeoutSeconds: 10
#          resources:
#            requests:
#              memory: "512Mi"
#              cpu: "200m"
#            limits:
#              memory: "800Mi"
#              cpu: "500m"