version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: db_msvc_usuarios
      #      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: robertraul/usuarios
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
#    env_file: ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_NAME: db_msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD:
      CURSOS_URL: ec2-54-196-250-86.compute-1.amazonaws.com:8002
      #msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

volumes:
  data-mysql:
    name: data-mysql
networks:
  spring:
    name: spring
